version: '3.8'

services:
  web:
    image: python:3.11-alpine
    working_dir: /workspaces/qualidade-software-dama
    volumes:
      - .:/workspaces/qualidade-software-dama
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: tail -f /dev/null

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dama
      POSTGRES_USER: dama
      POSTGRES_PASSWORD: dama
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: