# Generated by Django 5.1 on 2024-09-13 17:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_denuncia', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao_denuncia', models.TextField()),
                ('idade_vitima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_local', models.CharField(blank=True, max_length=30, null=True)),
                ('relacao_autor', models.CharField(blank=True, max_length=30, null=True)),
                ('zona_cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('vitima_tipo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField()),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('relato_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Relato', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto_comentario', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dama.relato')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioOng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=11, unique=True)),
                ('razao_social', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
                ('nome_completo', models.CharField(max_length=100)),
                ('cadastro_crp', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
