# Generated by Django 5.1 on 2024-08-17 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('relato_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_relato', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto_relato', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_comentario', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_id', models.UUIDField(editable=False)),
                ('texto_comentario', models.CharField(max_length=190)),
                ('relato_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dama.relato', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioOng',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dama.usuario')),
                ('cnpj', models.CharField(max_length=11, unique=True)),
                ('razao_social', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('dama.usuario',),
        ),
        migrations.CreateModel(
            name='UsuarioProfissional',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dama.usuario')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cadastro_crp', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('dama.usuario',),
        ),
        migrations.AddField(
            model_name='relato',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dama.usuario', unique=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('conteudo', models.TextField()),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('referencias', models.URLField(blank=True, null=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dama.usuario', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('denuncia_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_denuncia', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao_denuncia', models.CharField(blank=True, max_length=200)),
                ('idade_vitima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_local', models.CharField(blank=True, max_length=30, null=True)),
                ('relacao_autor', models.CharField(blank=True, max_length=30, null=True)),
                ('zona_cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('vitima_tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('denunciante_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dama.usuario', unique=True)),
            ],
        ),
    ]
