# Generated by Django 5.1 on 2024-08-20 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dama', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relato',
            old_name='texto_relato',
            new_name='Relato',
        ),
        migrations.RenameField(
            model_name='relato',
            old_name='data_relato',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='relato',
            name='usuario_id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='relato_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dama.relato'),
        ),
        migrations.AlterField(
            model_name='material',
            name='usuario_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dama.usuario'),
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
