# Generated by Django 5.1.3 on 2024-12-10 21:23

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20, unique=True)),
                ('contato', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('conselho', models.CharField(max_length=20, unique=True)),
                ('contato', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
