# Generated by Django 3.2.25 on 2024-11-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('publicador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20, unique=True)),
                ('conselho', models.CharField(max_length=20, unique=True)),
                ('contato', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ong',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20, unique=True)),
                ('contato', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('bio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
