# Generated by Django 5.1.3 on 2025-01-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
