# Generated by Django 5.1.3 on 2024-12-01 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profissional_nome_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
