# Generated by Django 5.1.3 on 2024-12-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_relato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='senha',
            field=models.CharField(max_length=50),
        ),
    ]
