# Generated by Django 5.1.3 on 2025-01-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ong_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='relato',
            name='status',
            field=models.CharField(choices=[('sub', 'Analise'), ('ok', 'Aprovada'), ('del', 'Deletada')], default='sub', max_length=8),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('sub', 'Analise'), ('ok', 'Aprovada'), ('del', 'Deletada')], default='sub', max_length=8),
        ),
    ]
